name: Flask App Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Verify `requirements.txt` exists
      - name: Verify requirements.txt exists
        run: |
          if [ ! -f requirements.txt ]; then
            echo "Error: requirements.txt not found. Please ensure it exists in the repository root."
            exit 1
          fi

      # Step 3: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Log in to Docker Hub (if pushing images to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t flask_app:${{ github.sha }} .

      # Step 7: Tag Docker image (for pushing to Docker Hub)
      - name: Tag Docker Image
        run: |
          docker tag flask_app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/flask_app:latest

      # Step 8: Push Docker image to Docker Hub (optional)
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask_app:latest

      # Step 9: Deploy container (local or remote server)
      - name: Deploy Docker Container
        run: |
          docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/flask_app:latest
